apiVersion: v1
kind: ConfigMap
metadata:
  name: rr1-config
  namespace: xrd
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname XRd-RR1
    username redhat
     group root-lr
     group cisco-support
     password redhat123
    interface GigabitEthernet0/0/0/0
     ipv4 address 192.168.86.251 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.11 255.255.255.255
    router static
     address-family ipv4 unicast
     0.0.0.0/0 192.168.86.1
    router bgp 100
     address-family ipv4 unicast
      redistribute connected
    neighbor-group as-100-rrc
     remote-as 100
     address-family ipv4 unicast
      route-reflector-client
    neighbor 192.168.86.241 use neighbor-group as-100-rrc
    neighbor 192.168.86.242 use neighbor-group as-100-rrc
    neighbor 192.168.86.243 use neighbor-group as-100-rrc
    neighbor 192.168.86.244 use neighbor-group as-100-rrc
    neighbor 192.168.86.245 use neighbor-group as-100-rrc
    neighbor 192.168.86.246 use neighbor-group as-100-rrc
    neighbor 192.168.86.252
     remote-as 100
     address-family ipv4 unicast

