apiVersion: v1
kind: ConfigMap
metadata:
  name: r1-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname R1
    username redhat
     group root-lr
     group cisco-support
     password 7 0214015F03071B701E1D
    interface GigabitEthernet0/0/0/0
     ipv4 address 10.10.12.1 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/1
     ipv4 address 10.10.13.1 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.1 255.255.255.255
    route-policy SID($SID)
      set label-index $SID
    end-policy
    router isis 100
      net 49.2025.5500.0001.00
      log adjacency changes
      address-family ipv4 unicast
        metric-style wide
        advertise passive-only
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 1        
      interface GigabitEthernet0/0/0/0
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/1
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.1
        address-family ipv4 unicast
          network 1.1.1.1/32 route-policy SID(1)
          allocate-label all
        address-family vpnv4 unicast
        neighbor-group RR
          remote-as 65001
          update-source Loopback0
          address-family ipv4 labeled-unicast
          address-family vpnv4 unicast
        neighbor 1.1.1.2
          use neighbor-group RR
        neighbor 1.1.1.3
          use neighbor-group RR
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
      traffic-eng
        pcc
          source-address ipv4 1.1.1.1
          pce address ipv4 1.1.1.101
            precedence 100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r2-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname R2
    username redhat
     group root-lr
     group cisco-support
     password redhat123
    interface GigabitEthernet0/0/0/0
     ipv4 address 10.10.12.2 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/2
     ipv4 address 10.10.23.2 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/3
     ipv4 address 10.10.24.2 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/102
     ipv4 address 10.10.102.2 255.255.255.0
     no shut
     interface loopback 0
     ipv4 address 1.1.1.2 255.255.255.255
    prefix-set any
      0.0.0.0/0
      end-set
    route-policy DROP_ALL
      if destination in any then
        drop
      endif
    end-policy
    router isis 100
      net 49.2025.5500.0002.00
      log adjacency changes
      address-family ipv4 unicast
        metric-style wide
        advertise passive-only
        propagate level 1 into level 2 route-policy DROP_ALL
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 2
      interface GigabitEthernet0/0/0/0
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/2
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/3
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/102
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.2
      ibgp policy out enforce-modifications
      address-family ipv4 unicast
        allocate-label all
      address-family vpnv4 unicast
      neighbor-group INLINE_RRC
        remote-as 65001
        update-source Loopback0
        address-family ipv4 labeled-unicast
          route-reflector-client
          next-hop-self
        address-family vpnv4 unicast
          route-reflector-client
      neighbor 1.1.1.1
        use neighbor-group INLINE_RRC
      neighbor 1.1.1.101
        use neighbor-group INLINE_RRC
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r3-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname R3
    username redhat
     group root-lr
     group cisco-support
     password 7 0214015F03071B701E1D
    interface GigabitEthernet0/0/0/1
     ipv4 address 10.10.13.3 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/2
     ipv4 address 10.10.23.3 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/3
     ipv4 address 10.10.35.3 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.3 255.255.255.255
    prefix-set any
      0.0.0.0/0
      end-set
    route-policy DROP_ALL
      if destination in any then
        drop
      endif
    end-policy
    router isis 100
      net 49.2025.5500.0003.00
      log adjacency changes
      address-family ipv4 unicast
        metric-style wide
        advertise passive-only
        propagate level 1 into level 2 route-policy DROP_ALL
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 3
      interface GigabitEthernet0/0/0/1
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/2
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/3
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.3
      ibgp policy out enforce-modifications
      address-family ipv4 unicast
        allocate-label all
      address-family vpnv4 unicast
      neighbor-group INLINE_RRC
        remote-as 65001
        update-source Loopback0
        address-family ipv4 labeled-unicast
          route-reflector-client
          next-hop-self
        address-family vpnv4 unicast
          route-reflector-client
      neighbor 1.1.1.1
        use neighbor-group INLINE_RRC
      neighbor 1.1.1.101
        use neighbor-group INLINE_RRC
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r4-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname R4
    username redhat
     group root-lr
     group cisco-support
     password 7 0214015F03071B701E1D
    interface GigabitEthernet0/0/0/0
     ipv4 address 10.10.46.4 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/2
     ipv4 address 10.10.45.4 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/3
     ipv4 address 10.10.24.4 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/104
     ipv4 address 10.10.104.4 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.4 255.255.255.255
    prefix-set any
      0.0.0.0/0
      end-set
    route-policy DROP_ALL
      if destination in any then
        drop
      endif
    end-policy
    router isis 100
      net 49.2025.5500.0004.00
      log adjacency changes
      address-family ipv4 unicast
        metric-style wide
        advertise passive-only
        propagate level 1 into level 2 route-policy DROP_ALL
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 4        
      interface GigabitEthernet0/0/0/0
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/2
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/3
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/104
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.4
      ibgp policy out enforce-modifications
      address-family ipv4 unicast
        allocate-label all
      address-family vpnv4 unicast
      neighbor-group INLINE_RRC
        remote-as 65001
        update-source Loopback0
        address-family ipv4 labeled-unicast
          route-reflector-client
          next-hop-self
        address-family vpnv4 unicast
          route-reflector-client
      neighbor 1.1.1.6
        use neighbor-group INLINE_RRC
      neighbor 1.1.1.101
        use neighbor-group INLINE_RRC
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r5-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname R5
    username redhat
     group root-lr
     group cisco-support
     password 7 0214015F03071B701E1D
    interface GigabitEthernet0/0/0/1
     ipv4 address 10.10.56.5 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/2
     ipv4 address 10.10.45.5 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/3
     ipv4 address 10.10.35.5 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.5 255.255.255.255
    prefix-set any
      0.0.0.0/0
      end-set
    route-policy DROP_ALL
      if destination in any then
        drop
      endif
    end-policy
    router isis 100
      net 49.2025.5500.0005.00
      log adjacency changes
      address-family ipv4 unicast
        metric-style wide
        advertise passive-only
        propagate level 1 into level 2 route-policy DROP_ALL
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 5
      interface GigabitEthernet0/0/0/1
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/2
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/3
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.5
      ibgp policy out enforce-modifications
      address-family ipv4 unicast
        allocate-label all
      address-family vpnv4 unicast
      neighbor-group INLINE_RRC
        remote-as 65001
        update-source Loopback0
        address-family ipv4 labeled-unicast
          route-reflector-client
          next-hop-self
        address-family vpnv4 unicast
          route-reflector-client
      neighbor 1.1.1.6
        use neighbor-group INLINE_RRC
      neighbor 1.1.1.101
        use neighbor-group INLINE_RRC
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r6-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname R6
    username redhat
     group root-lr
     group cisco-support
     password 7 0214015F03071B701E1D
    interface GigabitEthernet0/0/0/0
     ipv4 address 10.10.46.6 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/1
     ipv4 address 10.10.56.6 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.6 255.255.255.255
    route-policy SID($SID)
      set label-index $SID
    end-policy
    router isis 100
      net 49.2025.5500.0006.00
      log adjacency changes
      address-family ipv4 unicast
        metric-style wide
        advertise passive-only
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 6
      interface GigabitEthernet0/0/0/0
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/1
        circuit-type level-1
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.6
        address-family ipv4 unicast
          network 1.1.1.6/32 route-policy SID(6)
          allocate-label all
        address-family vpnv4 unicast
        neighbor-group RR
          remote-as 65001
          update-source Loopback0
          address-family ipv4 labeled-unicast
          address-family vpnv4 unicast
        neighbor 1.1.1.4
          use neighbor-group RR
        neighbor 1.1.1.5
          use neighbor-group RR
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
      traffic-eng
        pcc
          source-address ipv4 1.1.1.6
          pce address ipv4 1.1.1.101
          precedence 100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pce1-config
  namespace: sr-pce
  annotations:

  labels:
    #helm.sh/chart: xrd-control-plane-1.0.1
    #app.kubernetes.io/name: xrd-control-plane
    #app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.8.1"
    #app.kubernetes.io/managed-by: Helm
data:
  startup.cfg: |
    hostname PCE1
    username redhat
     group root-lr
     group cisco-support
     password 7 0214015F03071B701E1D
    pce
      address ipv4 1.1.1.101
    interface GigabitEthernet0/0/0/102
     ipv4 address 10.10.102.101 255.255.255.0
     no shut
    interface GigabitEthernet0/0/0/104
     ipv4 address 10.10.104.101 255.255.255.0
     no shut
    interface loopback 0
     ipv4 address 1.1.1.101 255.255.255.255
    route-policy SID($SID)
      set label-index $SID
    end-policy
    router isis 100
      net 49.2025.5500.0101.00
      log adjacency changes
        address-family ipv4 unicast
          metric-style wide
          advertise passive-only
        segment-routing mpls sr-prefer
      interface Loopback0
        passive
        address-family ipv4 unicast
        prefix-sid index 101
      interface Loopback0
        passive
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/102
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
      interface GigabitEthernet0/0/0/104
        circuit-type level-2-only
        point-to-point
        address-family ipv4 unicast
    router bgp 65001
      bgp router-id 1.1.1.101
      address-family link-state link-state
      address-family ipv4 unicast
          network 1.1.1.101/32 route-policy SID(101)
        allocate-label all
      address-family vpnv4 unicast
      neighbor-group RRC
        remote-as 65001
        update-source Loopback0
        address-family ipv4 labeled-unicast
          route-reflector-client
        address-family vpnv4 unicast
          route-reflector-client
      neighbor 1.1.1.2
        use neighbor-group RRC
      neighbor 1.1.1.3
        use neighbor-group RRC
      neighbor 1.1.1.4
        use neighbor-group RRC
      neighbor 1.1.1.5
        use neighbor-group RRC
    no mpls ldp
    mpls oam
    segment-routing
      global-block 16000 17000
      traffic-eng
